
spring:
  redis:
    host: localhost
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sni?serverTimezone=GMT%2B8
    username: root
    password: whoareyou
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
          max-idle: 10
          max-wait-millis: 10000
          min-idle: 5
          initial-size: 5

  main:
    web-application-type: none

mybatis:
  mapper-locations: "classpath:mapper/*.xml"

server:
  port: 8081

zookeeper:
  address: zookeeper://127.0.0.1:2181
  group: sni
  timeout: 60000
